---
repos:
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Validate Commit Message
        entry: bash -c 'regex=\'^(feat|bugfix|hotfix):.*$\' && if ! grep -iqE \"$regex\" \"$1\"; then echo \"Invalid commit message(pre-commit validation)\"; exit 1; fi'
        language: system
        files: \.git/COMMIT_EDITMSG

      - id: black
        name: black
        entry: black --config pre_commit/black.cfg .
        language: system
        types: [ python ]

      - id: isort
        name: isort
        entry: isort --settings-file  pre_commit/isort.cfg .
        language: system
        types: [ python ]

      - id: flake8
        name: flake8
        entry: flake8 --config pre_commit/flake8.cfg .
        language: system
        types: [ python ]
