"""initial info_commands, trigger_event and trigger tables

Revision ID: 29d1bc6d0fb9
Revises:
Create Date: 2024-04-18 15:14:07.381323

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "29d1bc6d0fb9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "info_commands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("info", sa.String(length=4096), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trigger_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "match_mode", sa.Enum("text", "regex", name="matchmodeenum"), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("event", sa.String(length=4096), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "triggers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "media_type",
            sa.Enum(
                "TEXT",
                "PHOTO",
                "ANIMATION",
                "STICKER",
                "VIDEO",
                "VOICE",
                "AUDIO",
                name="mediatypeenum",
            ),
            nullable=False,
        ),
        sa.Column("media", sa.String(length=4096), nullable=False),
        sa.Column("trigger_event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trigger_event_id"], ["trigger_events.id"], ondelete="Cascade"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("triggers")
    op.drop_table("trigger_events")
    op.drop_table("info_commands")
    # ### end Alembic commands ###
