name: CI

on:
  pull_request:
    branches: [ 'main', 'dev' ]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_u
          POSTGRES_PASSWORD: test_p
        ports:
          - 6999:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 15s

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Export variables from secret
        run: |
          echo ${{ secrets.ENV_FOR_TESTS }} | base64 --decode > $GITHUB_ENV
      - name: Run tests
        run: pytest
