name: Deploy
 
on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: test job
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ~/candy_uncle
          touch test.txt
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY}}
