name: CD
 
on:

  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Apply ssh actions
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd ~/candy_uncle
          git pull
          make prod
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY}}
