name: Deploy
 
on:
  push:
    branches: [ dev ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: test job
      uses: appleboy/ssh-action@v0.1.10
      with:
        key: ${{ secrets.SSHKEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
            cd ~/candy_uncle
            touch test.txt
